# Generated by Django 4.2.4 on 2024-02-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_functionalarea_industrytype'),
        ('jobs', '0002_jobpositions_wishlist_delete_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpositions',
            old_name='location',
            new_name='benefits',
        ),
        migrations.RemoveField(
            model_name='jobpositions',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='functional_area',
            field=models.ManyToManyField(to='Dashboard.functionalarea'),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='industry_type',
            field=models.ManyToManyField(to='Dashboard.industrytype'),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='international_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='job_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='max_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='maxsalary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='min_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='minsalary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='operational_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='position_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='shipment_expertise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
