# Generated by Django 4.2.4 on 2024-02-04 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_functionalarea_industrytype'),
        ('jobs', '0003_rename_location_jobpositions_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpositions',
            name='functional_area',
        ),
        migrations.AddField(
            model_name='jobpositions',
            name='functional_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.functionalarea'),
        ),
    ]
