# Generated by Django 5.0.1 on 2024-02-05 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_functionalarea_industrytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionalarea',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.industrytype'),
        ),
    ]
