# Generated by Django 5.0.1 on 2024-02-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_functionalarea_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalarea',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
