# Generated by Django 4.2.4 on 2024-02-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_paymentdetails_skillset_user_end_date_user_pincode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='designation',
            new_name='authorized_person',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='company_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='state',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
