# Generated by Django 5.0.1 on 2024-02-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_recruiter_employess_recruiter_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='map_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
