# Generated by Django 5.0.1 on 2024-02-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_alter_recruiter_map_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='wesbsite',
            new_name='website',
        ),
    ]
